"""
ml/linkage.py — T2.4 Fellegi-Sunter EM record linkage.

Ported (not vendored) from fast-er's `faster/estimation.py`
(https://github.com/JacobMorrier/fast-er), operator-directed integration
under the upstream MIT license, reproduced verbatim below:

    Copyright (c) 2024 Jacob Morrier, Sulekha Kishore, and R. Michael Alvarez

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

Deliberate deviations from upstream (this is a PORT, not a vendor copy —
this is exactly why we didn't just `pip install` it):
  * Seeded: the Dirichlet initializations draw from
    `np.random.default_rng(self.seed)` (constructor kwarg `seed: int = 7`,
    consumed only inside `fit()`, never re-seeded at call time) instead of
    upstream's bare `np.random.dirichlet`, which mutates and reads the
    global numpy RNG state — unreproducible across processes/runs, fatal
    for an audited system where two runs on the same data must agree.
  * No `print()`: upstream's convergence message becomes
    `log.info(...)` on logger "liquiditybot.ml.linkage".
  * float64 throughout `_posterior` (upstream's `_match_probability` used
    float32 for `cond_prob`, which is unnecessary precision loss on a
    corpus small enough that this class runs in milliseconds regardless).
  * The degenerate Bayes cell (`den == 0` — both latent classes assign
    exactly zero likelihood to an observed pattern under the current fit,
    only reachable in sparse/degenerate corners of pattern space) is
    guarded with `np.errstate` + `np.nan_to_num(..., nan=0.0)` rather than
    left to propagate a NaN posterior for that pattern.
  * Blocking, the CUDA/CuPy string-similarity kernels, and the pandas
    dependency are stripped entirely: this repo's pair space is a few
    thousand (asset, side, time-window)-restricted candidates, already
    reduced to that scale before this class ever sees it — none of
    upstream's record-linkage-at-scale machinery applies.

Fellegi-Sunter latent-class model — brief background
--------------------------------------------------------
Every compared PAIR of records (here: a live close vs. a candidate row)
is reduced to a PATTERN gamma = (gamma_1, ..., gamma_K) of discrete
similarity levels across K compared variables — fuzzy variables take 3
levels {0, 1, 2} (least to most similar), exact variables take 2 levels
{0, 1} (differ / agree). The model treats every pair as generated by one
of two latent classes, match (M) or non-match (U). The full E-step /
M-step / convergence update equations this module implements are
written into the `FellegiSunterEM` class docstring itself (not
duplicated here) — see `help(FellegiSunterEM)`.
"""

import itertools
import logging

import numpy as np

log = logging.getLogger("liquiditybot.ml.linkage")


def discretize_fuzzy(values, near: float, far: float) -> np.ndarray:
    """Discretize a continuous |delta| into 3 similarity levels: 2 (most
    similar) when |v| <= near, 1 when |v| <= far, 0 (least similar)
    beyond far. Ascending in similarity, matching the match-class
    (`pi_m`) init, which puts its mass on the HIGH end of this scale."""
    v = np.abs(np.asarray(values, dtype=np.float64))
    return np.where(v <= near, 2, np.where(v <= far, 1, 0)).astype(int)


def discretize_exact(a, b) -> np.ndarray:
    """Discretize an exact-match variable: 1 where a[i] == b[i], else 0."""
    return (np.asarray(a) == np.asarray(b)).astype(int)


class FellegiSunterEM:
    """Fellegi-Sunter latent-class model, fit by EM over a table of
    (pattern, count) pairs. `counts[i]` is the observed number of
    compared pairs whose discrete similarity pattern is `patterns[i]`;
    the class never sees raw pairs, only this aggregated table. See the
    module docstring for the upstream MIT notice and the deliberate
    port deviations (seeding, no print, float64, the den==0 guard).

    `k_fuzzy` fuzzy (3-level) variables are enumerated before `k_exact`
    exact (2-level) variables in every pattern row — this ordering is
    load-bearing: callers building `counts` must enumerate patterns via
    `FellegiSunterEM(k_fuzzy, k_exact, np.zeros(n_patterns)).patterns`
    (or replicate `itertools.product` in the same order) to line their
    counts up correctly.

    Conditional on latent class (match M / non-match U), similarity
    levels across variables are assumed CONDITIONALLY INDEPENDENT (the
    "naive Bayes" simplifying assumption Fellegi-Sunter itself makes),
    each governed by its own per-variable, per-class multinomial
    `pi_m[k]` / `pi_u[k]` over that variable's levels, with
    unconditional match probability `lambda = P(M)`:

        P(gamma | M) = prod_k pi_m[k][gamma_k]
        P(gamma | U) = prod_k pi_u[k][gamma_k]

    E-step — posterior match probability for pattern gamma
    (`_posterior`), computed in log space (sum of logs, then one
    exponentiation) so a product over many variables never underflows:

        log P(gamma|M) = sum_k log(pi_m[k][gamma_k])
        log P(gamma|U) = sum_k log(pi_u[k][gamma_k])

        xi(gamma) = P(M | gamma)
                  = (lambda * P(gamma|M))
                    / (lambda * P(gamma|M) + (1 - lambda) * P(gamma|U))

      `den == 0` (both classes assign zero mass to this pattern under
      the current fit) is guarded to `xi(gamma) = 0` rather than a
      propagated NaN.

    M-step — let `n(gamma)` be the observed COUNT of pattern gamma
    (this class fits on a pattern x count table, never raw pairs); sums
    range over the distinct patterns enumerated by `patterns`, weighted
    by count:

        lambda_new = sum_gamma [xi(gamma) * n(gamma)] / sum_gamma n(gamma)

        pi_m[k][l]_new = sum_{gamma: gamma_k == l} [n(gamma) * xi(gamma)]
                         / sum_gamma [n(gamma) * xi(gamma)]

        pi_u[k][l]_new = sum_{gamma: gamma_k == l} [n(gamma) * (1 - xi(gamma))]
                         / sum_gamma [n(gamma) * (1 - xi(gamma))]

    Convergence: the largest absolute change in any single `pi_m[k][l]`
    or `pi_u[k][l]` entry between successive M-steps falls below `tol`
    (matching upstream, `lambda` itself is not part of the convergence
    test).

    Initialization deliberately breaks the label-switching symmetry
    every two-component mixture faces: `pi_u` (non-match) is
    initialized with mass concentrated on the LOW-similarity levels
    (descending per variable), `pi_m` (match) with mass concentrated on
    the HIGH-similarity level (ascending per variable) — encoding the
    one substantive assumption the whole method rests on: agreeing
    pairs are more likely to be matches.
    """

    def __init__(self, k_fuzzy: int, k_exact: int, counts, seed: int = 7):
        self.k_fuzzy, self.k_exact = int(k_fuzzy), int(k_exact)
        self.counts = np.asarray(counts, dtype=np.float64)
        self.seed = int(seed)
        self.patterns = self._patterns()          # (P, K) int matrix
        if len(self.counts) != len(self.patterns):
            raise ValueError(
                f"counts has {len(self.counts)} entries but k_fuzzy="
                f"{self.k_fuzzy}, k_exact={self.k_exact} enumerates "
                f"{len(self.patterns)} patterns")
        self.lam: float = 0.0
        self._pi_m: list = []
        self._pi_u: list = []
        self.converged = False
        self._fitted = False

    def _levels(self) -> list:
        return [3] * self.k_fuzzy + [2] * self.k_exact

    def _patterns(self) -> np.ndarray:
        levels = self._levels()
        return np.array(list(itertools.product(
            *(range(n) for n in levels))), dtype=int)

    def _posterior(self) -> np.ndarray:
        """E-step / final posterior: xi(gamma) = P(match | gamma) for
        every enumerated pattern, in log space per class then Bayes'
        rule (see class docstring). float64 throughout (upstream used
        float32)."""
        levels = self._levels()
        cond_prob = np.zeros((2, len(self.patterns)), dtype=np.float64)
        with np.errstate(divide="ignore", invalid="ignore"):
            for m, pi in enumerate((self._pi_u, self._pi_m)):
                for k in range(len(levels)):
                    cond_prob[m, :] += np.log(pi[k][self.patterns[:, k]])
                cond_prob[m, :] = np.exp(cond_prob[m, :])
            num = self.lam * cond_prob[1, :]
            den = num + (1.0 - self.lam) * cond_prob[0, :]
            xi = num / den
        # degenerate cell: both classes assign zero mass to this pattern
        # under the current fit (den == 0) -> NaN from 0/0. Guarded to 0
        # rather than propagated (a pattern no class explains is not
        # evidence of a match).
        return np.nan_to_num(xi, nan=0.0)

    def fit(self, tol: float = 1e-4, max_iter: int = 5000) \
            -> "FellegiSunterEM":
        """Run EM to convergence (or `max_iter`). One-shot: a fitted
        instance refuses a second `fit()` call (raises RuntimeError) —
        callers wanting a re-fit build a fresh instance, so a fitted
        model's parameters can never be silently perturbed out from
        under a caller already holding its `match_posterior`."""
        if self._fitted:
            raise RuntimeError("FellegiSunterEM.fit() is one-shot")
        rng = np.random.default_rng(self.seed)
        levels = self._levels()
        # non-match mass on LOW similarity levels (descending per var)
        self._pi_u = [-np.sort(-rng.dirichlet(np.arange(1, n * 50 + 1, 50)))
                      for n in levels]
        # match mass on HIGH similarity levels (ascending per var)
        self._pi_m = [np.sort(rng.dirichlet(np.arange(1, n * 50 + 1, 50)))
                      for n in levels]
        self.lam = 0.1
        total = float(np.sum(self.counts))
        converged = False
        it = 0
        while not converged and it < max_iter:
            it += 1
            ksi = self._posterior()                        # E-step
            with np.errstate(divide="ignore", invalid="ignore"):
                new_lam = float(np.dot(ksi, self.counts) / total)
                m_denom = np.dot(ksi, self.counts)
                new_pi_m = [np.fromiter(
                    (np.dot((self.patterns[:, k] == lvl) * self.counts, ksi)
                     for lvl in range(n)), dtype=np.float64) / m_denom
                    for k, n in enumerate(levels)]
                u_denom = np.dot(1.0 - ksi, self.counts)
                new_pi_u = [np.fromiter(
                    (np.dot((self.patterns[:, k] == lvl) * self.counts,
                            1.0 - ksi) for lvl in range(n)),
                    dtype=np.float64) / u_denom
                    for k, n in enumerate(levels)]
            old_flat = np.concatenate(
                [np.concatenate(self._pi_u), np.concatenate(self._pi_m)])
            new_flat = np.concatenate(
                [np.concatenate(new_pi_u), np.concatenate(new_pi_m)])
            if np.max(np.abs(new_flat - old_flat)) < tol:
                converged = True
            self.lam, self._pi_u, self._pi_m = new_lam, new_pi_u, new_pi_m
        self.converged = converged
        log.info("linkage EM %s in %d iter(s)",
                  "converged" if converged else "hit max_iter", it)
        self._fitted = True
        return self

    @property
    def match_posterior(self) -> np.ndarray:
        """P(match | pattern) for every row of `patterns`, in the same
        order. Requires `fit()` to have run."""
        if not self._fitted:
            raise RuntimeError("call fit() first")
        return self._posterior()
